const $ = (selector) => document.querySelector(selector);
const API_BASE = (window.TRAFFIC_API_BASE || "").replace(/\/$/, "");
const UPLOAD_ENDPOINT = `${API_BASE}/upload`;
const HEALTH_ENDPOINT = `${API_BASE}/health`;
let selectedFile = null;
let previewUrl = null;

function setApiStatus(text, online) { $("#apiStatus").textContent = text; $("#apiDot").classList.toggle("offline", !online); }
async function checkBackend(){try{const r=await fetch(HEALTH_ENDPOINT);if(!r.ok)throw Error();setApiStatus("BACKEND ONLINE",true)}catch{setApiStatus("BACKEND OFFLINE",false)}}
function formatBytes(bytes){if(bytes<1024*1024)return `${(bytes/1024).toFixed(1)} KB`;return `${(bytes/1024/1024).toFixed(1)} MB`}
function selectFile(file){if(!file)return;const ext=file.name.toLowerCase().split(".").pop();if(!["mp4","avi","mov","mkv"].includes(ext)){alert("Please choose an MP4, AVI, MOV or MKV traffic video.");return}selectedFile=file;$("#fileName").textContent=file.name;$("#fileMeta").textContent=`${formatBytes(file.size)} • Ready for analysis`;$("#analyzeBtn").disabled=false;$("#dropZone").classList.add("has-file");
if(previewUrl)URL.revokeObjectURL(previewUrl);previewUrl=URL.createObjectURL(file);$("#inputPreview").src=previewUrl;$("#previewWrap").hidden=false;resetResults();scrollToPreview()}
function scrollToPreview(){setTimeout(()=>$("#upload-card")?.scrollIntoView({behavior:"smooth",block:"center"}),50)}
function resetResults(){$("#totalVehicles").textContent="—";$("#busiestRegion").textContent="—";$("#congestionScore").textContent="—";$("#persistence").textContent="—";$("#severityBadge").textContent="WAITING FOR FOOTAGE";$("#severityBadge").className="severity-badge";$("#regionStatus").textContent="NO DATA";$("#videoStatus").textContent="AWAITING ANALYSIS";$("#recommendationBox").innerHTML=`<div class="insight-icon">✦</div><div><strong>Run an analysis to generate an insight.</strong><p>The engine compares occupancy and movement across regions to identify the strongest potential hotspot.</p></div>`;$("#regionList").innerHTML=`<div class="empty-state">Regional results will appear after analysis.</div>`;$("#regionChart").innerHTML=`<div class="empty-state">Run an analysis to populate the signal.</div>`}
function congestionLabel(score){if(score>=.6)return["HIGH HOTSPOT","danger"];if(score>=.3)return["MODERATE","warning"];return["LOW","safe"]}
function renderAnalysis(result){const score=Number(result.congestion_score||0);const[label,level]=congestionLabel(score);$("#totalVehicles").textContent=result.vehicles_detected??"—";$("#busiestRegion").textContent=result.busiest_region||"—";$("#congestionScore").textContent=score.toFixed(3);$("#persistence").textContent=`${Number(result.bottleneck_persistence||0).toFixed(1) }%`;$("#severityBadge").textContent=label;$("#severityBadge").className=`severity-badge ${level}`;$("#regionStatus").textContent=`${result.regions?.length||0} REGIONS ANALYSED`;$("#videoStatus").textContent="ANNOTATED VIDEO NEXT";$("#recommendationBox").innerHTML=`<div class="insight-icon ${level}">✦</div><div><strong>${escapeHtml(result.busiest_region||"Unknown region")} identified as the strongest hotspot</strong><p>${escapeHtml(result.recommendation||"No recommendation was returned by the analysis engine.")}</p></div>`;renderRegions(result.regions||[]);renderChart(result.regions||[]);$("#resultsSection").scrollIntoView({behavior:"smooth",block:"start"})}
function renderProcessedVideo(result) {
    const video = $("#processedVideo");

    if (result.annotated_video) {
        video.src = `${API_BASE}${result.annotated_video}`;
        video.load();
    }
}
function renderRegions(regions){if(!regions.length){$("#regionList").innerHTML=`<div class="empty-state">No regional observations were returned.</div>`;return}$("#regionList").innerHTML=regions.map(r=>{const score=Number(r.congestion_score||0);const width=Math.max(2,Math.min(100,score*100));const[label,level]=congestionLabel(score);return `<article class="region-row"><div class="region-main"><div><strong>${escapeHtml(r.region)}</strong><span class="region-tag ${level}">${label}</span></div><small>Occupancy ${Number(r.average_occupancy||0).toFixed(2)} • Movement ${Number(r.average_movement||0).toFixed(2)} px/frame</small></div><div class="score-wrap"><b>${score.toFixed(3)}</b><div class="mini-bar"><span style="width:${width}%"></span></div></div></article>`}).join("")}
function renderChart(regions){if(!regions.length){$("#regionChart").innerHTML=`<div class="empty-state">No regional data available.</div>`;return}const max=Math.max(...regions.map(r=>Number(r.congestion_score||0)),.001);$("#regionChart").innerHTML=`<div class="bars">${regions.map(r=>{const score=Number(r.congestion_score||0);const h=Math.max(7,score/max*100);return `<div class="bar-group"><div class="bar-value">${score.toFixed(3)}</div><div class="bar-track"><span style="height:${h}%"></span></div><b>${escapeHtml(r.region.replace("Bottom-","B-").replace("Top-","T-"))}</b></div>`}).join("")}</div>`}
function escapeHtml(v){return String(v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function setProgress(p,text){$("#progressBar").style.width=`${p}%`;$("#progressPercent").textContent=`${Math.round(p)}%`;$("#progressText").textContent=text}
async function analyzeTraffic(){if(!selectedFile)return;const btn=$("#analyzeBtn");$("#progressWrap").hidden=false;btn.disabled=true;setProgress(8,"Uploading traffic footage...");setApiStatus("ANALYSING",true);try{const form=new FormData();form.append("file",selectedFile);setProgress(25,"Video received. YOLO tracking is running...");const response=await fetch(UPLOAD_ENDPOINT,{method:"POST",body:form});if(!response.ok)throw Error(await response.text()||`Server returned ${response.status}`);setProgress(85,"Traffic analytics complete. Preparing results...");const payload=await response.json();renderAnalysis(payload.analysis||{});renderProcessedVideo(payload.analysis||{});setProgress(100,"Analysis complete.");setApiStatus("BACKEND ONLINE",true)}catch(error){console.error(error);setProgress(100,"Analysis failed. Check the backend and try again.");setApiStatus("BACKEND ERROR",false);alert(`Traffic analysis failed.\n\n${error.message}`)}finally{btn.disabled=false}}
$("#chooseVideo").addEventListener("click",()=>$("#videoInput").click());$("#videoInput").addEventListener("change",e=>selectFile(e.target.files[0]));$("#analyzeBtn").addEventListener("click",analyzeTraffic);["dragenter","dragover"].forEach(n=>$("#dropZone").addEventListener(n,e=>{e.preventDefault();$("#dropZone").classList.add("dragging")}));["dragleave","drop"].forEach(n=>$("#dropZone").addEventListener(n,e=>{e.preventDefault();$("#dropZone").classList.remove("dragging")}));$("#dropZone").addEventListener("drop",e=>selectFile(e.dataTransfer.files[0]));
function updateClock(){const now=new Date();$("#clock").textContent=now.toLocaleTimeString("en-IN",{hour12:false});$("#footerTime").textContent=now.toLocaleDateString("en-IN",{day:"2-digit",month:"short",year:"numeric"}).toUpperCase()}
function setupReveal(){const items=document.querySelectorAll(".reveal");if(!("IntersectionObserver"in window)){items.forEach(i=>i.classList.add("visible"));return}const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add("visible");observer.unobserve(e.target)}}),{threshold:.08});items.forEach(i=>observer.observe(i))}
setupReveal();updateClock();setInterval(updateClock,1000);checkBackend();
